config/routes.rb
ElasticMicrodata::Application.routes.draw do

  resources :itemtypes

  root :to => 'itemtypes#index'

end

app/models/page.rb
class Page

  include Tire::Model::Persistence  

  property :url, :type => :string, :index => :not_analyzed
  property :sitemap, :type => :string, :index => :not_analyzed
  property :lastmod, :type => :date
  property :title, :type => :string
  property :description, :type => :string
  property :microdata, :type => :object
  property :itemtypes, :type => :string, :index => :not_analyzed
  property :itemprops, :type => :string, :index => :not_analyzed

  def self.build(sitemap_url, url, html)
    items = Microdata::Document.new(html, url).extract_items
    hash = {}
    hash[:items] = items.map do |item|
      item.to_hash
    end
    itemtypes = extract_itemtypes(items).uniq
    Page.create :sitemap => sitemap_url, 
                :microdata => hash, 
                :id => url, :itemtypes => itemtypes
  end

  private

  def self.extract_itemtypes(items)
    items.map do |item|      
      nested_types = []
      item.properties.each do |property, values|
        item_values = values.select do |value|
          value.is_a?(Microdata::Item) ? true : false
        end
        nested_types << extract_itemtypes(item_values)                 
      end
      extracted_types = [item.type ]
      extracted_types << nested_types
    end.flatten.compact
  end

end

Page.tire.create_elasticsearch_index

app/models/sitemap.rb
class Sitemap
  include Tire::Model::Persistence

  property :url, :index => :not_analyzed, :type => :string
  
  def crawl
    sitemap_xml = open(url).read
    if sitemap_xml.include?('sitemapindex')
      Nokogiri::HTML(sitemap_xml).xpath('//loc').each do |sitemap_loc|
        sitemap_xml = open(sitemap_loc.text).read
        index_sitemap(sitemap_xml)
      end
    else
      index_sitemap(sitemap_xml)
    end
  end

  private

  def index_sitemap(sitemap_xml)
    begin
      sitemap = Zlib::GzipReader.new( StringIO.new(sitemap_xml) ).read
    rescue => e
      sitemap = sitemap_xml
    end
    Nokogiri::HTML(sitemap).xpath('//loc').each_with_index do |loc, index|
      url = loc.content
      tries = 0
      begin
        if tries < 10
          sleep tries 
          open(url) do |f|
            Page.build(@url, url, f) 
          end
        end
      rescue => e 
        puts e
        puts e.backtrace
        puts "Error with: #{url}"
        tries += 1
        retry
      end
      puts url
    end
  end

end

Sitemap.create_elasticsearch_index

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/itemtypes_controller.rb
class ItemtypesController < ApplicationController
  def index
    search = Tire.search(
      'pages',
      :query => {
        :match_all => { },        
      }, 
      :facets => {
        :type => {
          :terms =>  {
            "field" => "itemtypes",
            "size" => 25
          }
        }
      }
    )
    @itemtypes = search.results.facets['type']['terms']
  end

  def show
    page = params["page"] || 1
    @page = page.to_i
    from = (@page.to_i - 1) * 25
    query_string = %Q|http://schema.org/#{params[:id]}|
    search = Tire.search(
      :pages,
      :query => {
        :term => {
          :itemtypes => query_string
        },        
      },
      :size => 25,
      :from => from      
    )
    # TODO: here's an alternate query that seemed to work
    # search = Tire.search(
    #   :pages,
    #   :query => {
    #     :match_all => { },        
    #   },
    #   :filter => {
    #     "and" => [
    #       { "terms" => {"itemtypes" => [query_string]} }
    #     ]
    #   },
    #   :size => 25,
    #   :from => from      
    # )
    @results = search.results
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def coderay(text)
    CodeRay.scan(text, :json).div #(:css => :class)  
  end

end

app/helpers/itemtypes_helper.rb
module ItemtypesHelper
end

app/views/itemtypes/_facet.html.erb
<ol>
  <% facet.each do |value| %>
    <li><%= value['term'] %> (<%= value['count'] %>)</li>
  <% end -%>
</ol>

app/views/itemtypes/index.html.erb
<h1>Itemtypes</h1>

<ol>
  <% @itemtypes.each do |value| %>
    <li><%= link_to value['term'], itemtype_path(value['term'].split('/').last) %> (<%= value['count'] %>)</li>
  <% end -%>
</ol>

app/views/itemtypes/show.html.erb
<h1><%= link_to "Itemtype", itemtypes_path %>: <%= params['id'] %></h1>

<!-- <h2>Properties Facet</h2>

<%#= render :partial => 'facet', :locals => {:facet => @properties} %>

<hr> 

<h2>Names Facet</h2>
<%#= render :partial => 'facet', :locals => {:facet => @names} %>

<hr> -->

<p>Count: <%= @results.total %></p>

<ul id="page_results">
  <% @results.each_with_hit do |page,hit| %>
    <li>
      <%#= debug hit %>
      <%= link_to page.id, page.id, target: '_blank' %> 
      
      <% if hit['_source']['microdata']['items'].first['properties']['name'] %>
        <div>
          <%= hit['_source']['microdata']['items'].first['properties']['name'].join(' | ') %>
        </div>
      <% end -%>
      <% if hit['_source']['microdata']['items'].first['properties']['thumbnailUrl'] %>
        <div>
          <%= image_tag hit['_source']['microdata']['items'].first['properties']['thumbnailUrl'].first, :width => 300 %>
        </div>
      <% elsif hit['_source']['microdata']['items'].first['properties']['image'] %>
        <div>
          <%= image_tag hit['_source']['microdata']['items'].first['properties']['image'].first, :width => 300 %>
        </div>
      <% end -%>

<%= coderay(JSON.pretty_generate(hit['_source']['microdata'])).html_safe %>


    </li>
  <% end -%>
</ul>

<%= link_to 'next page', itemtype_path(params['id'], :page => @page + 1) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ElasticMicrodata</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>